# Generated by Django 5.1.1 on 2024-09-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
