# Generated by Django 5.1.1 on 2024-10-02 06:47

import core.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_category_image_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.jpg', storage=core.storage_backend.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', storage=core.storage_backend.PublicMediaStorage(), upload_to=''),
        ),
    ]
